FROM node:24.13.1-alpine AS base

FROM base AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app/web

COPY package.json yarn.lock* ./
RUN --mount=type=cache,target=/usr/local/share/.cache/yarn\
  yarn install --production=false

FROM base AS builder
WORKDIR /app/web

COPY --from=deps /app/web/node_modules ./node_modules
COPY . .

ENV NODE_ENV=production

RUN echo $NODE_ENV

RUN --mount=type=cache,target=/app/.next/cache \
  yarn build

FROM base AS runner
WORKDIR /app/web

ENV NODE_ENV=production
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

COPY --from=builder --chown=node:node /app/web/public ./public
COPY --from=builder --chown=node:node /app/web/.next/standalone ./
COPY --from=builder --chown=node:node /app/web/.next/static ./.next/static

USER node

EXPOSE 3000

CMD ["node", "server.js"]
